### ISSUE TITLE
Occasional missing markers when expanding cluster markers

### ISSUE THREAD

**Issue by madwort** [WoodlandsCoUk/components#14]
Sometimes seeing a cluster expand but one individual wood marker missing until zooming in more, e.g.

https://tom.woodlands.co.uk/buying-a-wood/northern-scotland/map#14.86/57.29131/-3.83798

As seen on Firefox/macOS:

https://user-images.githubusercontent.com/2082895/111794553-3e944400-88be-11eb-8b19-cd498f51aa89.mov

Not spotted anything in the console, so (unfortunately) may not be the same marker image file loading issue as last time.

**Comment by madwort** [comment]
Due to having the dynamic left hand column, I think this isn't a show-stopper right now, but will try to fix.

**Comment by trovster** [comment]
Possibly because it's very close to the other marker and therefore falling in to some sort of grouping level we're not taking to account of in the settings?

**Comment by madwort** [comment]
yeah quite possibly!

**Comment by trovster** [comment]
Did this get resolved?

**Comment by madwort** [comment]
Yes I think this is resolved
